name: doctor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_slidable: ^0.6.0

  provider: ^5.0.0

  cupertino_icons: ^0.1.3


  calculess: ^1.0.2
  vector_math: ^2.1.0
  math_expressions: ^2.1.1




dev_dependencies:

#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/