name: doctor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.3

  flutter_slidable: ^0.6.0
  provider: ^5.0.0
  #url_launcher: 5.7.2
  url_launcher: 6.0.9
  firebase_auth: "^3.0.1"
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_core: ^1.4.0
  image_picker: ^0.8.3+2


dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/


  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Exo2
      fonts:
        - asset: assets/fonts/static/Exo2-bold.ttf
          weight: 700
        - asset: assets/fonts/static/Exo2-Italic.ttf
          style: italic
        - asset: assets/fonts/static/Exo2-BlackItalic.ttf
          weight: 100